# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Florida Water
tagline:          'swamp soul'
description:      'written in running water'
url:              http://0bviouSquirre1.github.io
baseurl:          /

author:
  name:           'Shannon'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
